version: "3.5"

services:
  nginx:
    build:
      args:
        ENVIRONMENT: "dev"
  api:
    build:
      dockerfile: docker/api/dev/Dockerfile
    volumes:
      - ./api:${API_PATH}
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
  web:
    build:
      dockerfile: docker/web/dev/Dockerfile
    volumes:
      - ./web:${WEB_PATH}
    environment:
      ENVIRONMENT: "dev"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - api
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1