version: "3.5"

services:
  nginx:
    build:
      args:
        ENVIRONMENT: ${ENV_PROD}
  api:
    environment:
      APP_ENV: ${ENV_PROD}
      APP_DEBUG: "false"
  web:
    environment:
      ENVIRONMENT: ${ENV_PROD}