version: "3.5"

services:
  nginx:
    build:
      args:
        ENVIRONMENT: "dev"
  api:
    build:
      dockerfile: docker/api/dev/Dockerfile
    volumes:
      - ./api:${API_PATH}
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
  web:
    build:
      dockerfile: docker/web/dev/Dockerfile
    volumes:
      - ./web:${WEB_PATH}