version: "3.5"

services:
  nginx:
    container_name: poker_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - api
      - web
  mysql:
    container_name: poker_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - api
  api:
    container_name: poker_api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        API_PATH: ${API_PATH}
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: ${API_DB_CONNECTION}
      DB_HOST: ${API_DB_HOST}
      DB_PORT: ${API_DB_PORT}
      DB_DATABASE: ${API_DB_DATABASE}
      DB_USERNAME: ${API_DB_USERNAME}
      DB_PASSWORD: ${API_DB_PASSWORD}
      APP_NAME: ${API_NAME}
      APP_KEY: ${API_KEY}
      APP_URL: ${API_URL}
      QUEUE_CONNECTION: ${API_QUEUE_CONNECTION}
      RABBITMQ_HOST: ${API_RABBITMQ_HOST}
      RABBITMQ_PORT: ${API_RABBITMQ_PORT}
      RABBITMQ_USER: ${API_RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${API_RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${API_RABBITMQ_VHOST}
    networks:
      - api
  mongo:
    container_name: poker_mongo
    image: mongo
    networks:
      - api
  rabbitMQ:
    container_name: poker_rabbitMQ
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - api
  web:
    container_name: poker_web
    build:
      dockerfile: docker/web/Dockerfile
      context: .
      args:
        WEB_PATH: ${WEB_PATH}
    networks:
      - web

networks:
  api:
    name: ${API_NETWORK}
    driver: bridge
  web:
    name: ${WEB_NETWORK}
    driver: bridge
