version: "3.5"

services:
  nginx:
    build:
      args:
        ENVIRONMENT: ${ENV_DEV}
  api:
    volumes:
      - ./api:${API_PATH}
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
  web:
    volumes:
      - ./web:${WEB_PATH}
    environment:
      ENVIRONMENT: ${ENV_DEV}
  dev-server:
    build:
      context: .
      dockerfile: docker/dev-server/Dockerfile
      args:
        WEB_PATH: ${WEB_PATH}
    ports:
      - "4000:4000"
    volumes:
      - ./web:${WEB_PATH}
    networks:
      - web
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    networks:
      - api
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1